
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
  labels:
    app: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: soumya
  template:
    metadata:
      name: jenkins
      labels:
        app: soumya
    spec:
      containers:
        - name: myjenkins
          image: jenkins/jenkins
